### ISSUE TITLE
ARMv8 Compilation Question/Issue

### ISSUE THREAD

**Issue by ljhsiun2** [misc0110/PTEditor#5]
I'm getting some errors building this kernel module on ARM hardware on the 5.8.6 kernel; in particular, I'm seeing 

```
ERROR: modpost: "swapper_pg_dir" undefined
ERROR: modpost: "pud_huge" undefined
ERROR: modpost: "pmd_huge" undefined
ERROR: modpost: "set_swapper_pgd" undefined
```

While I can fix this by just adding them to the symvers file, I'm not sure if that's the right approach or if there's a desire to work without modifying the upstream kernel.

What kernel or hardware was used to verify ARMv8 works?

**Comment by misc0110** [comment]
I use it on an NVIDIA Jetson TX1 which currently runs kernel 4.4.38. However, as I mainly work on x86, I haven't tested it on many kernel versions. Generally, it should work without modifying the kernel, and I try to ensure that this is the case.

I've (partly) reproduced your error messages on a Raspberry Pi 3 with kernel 5.4.51. Commit 0c8bd0557246ee8f08125e014fb53ef708fc7353 contains a workaround such that it compiles on this kernel. While it seems to work, it fails 3 of the unit tests (page.read, page.write, and paging.correct_root). I'm not yet sure what the problem is. 

Can you test whether this commit fixes at least the "swapper_pg_dir" and "set_swapper_pgd" error?

**Comment by ljhsiun2** [comment]
Yes, it fixes those errors.

A couple other compile errors were [here](https://github.com/misc0110/PTEditor/commit/0c8bd0557246ee8f08125e014fb53ef708fc7353#diff-e5ae2aaf1f176a3ae1d8a41d85f927f1R387) where I got rid of the ARM define/changed the reference to match up [here](https://elixir.bootlin.com/linux/v5.8.12/source/arch/arm64/include/asm/pgtable-types.h#L39), and also modified the pud/pmd_large to wrap the pud_huge/pmd_huge code directly.

With those additional changes, the unit tests work; I also don't know why it wouldn't work on an older kernel :) (Though I've definitely had previous problems with memory management in the ARM kernels, so it doesn't completely surprise me). 

Would you like me to submit a PR or would you find it simpler to fix the errors I mentioned?

**Comment by misc0110** [comment]
Thanks! Yes, I would appreciate if you could submit a PR :)
